import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import 'swiper/css';
import 'swiper/css/navigation';
import 'swiper/css/pagination';
import "aos/dist/aos.css";

import "splitting/dist/splitting.css";
import "splitting/dist/splitting-cells.css";

// Fonts
import { Martel } from 'next/font/google'
import { Work_Sans } from 'next/font/google'
import Footer from "@/components/Footer";

const martel = Martel({
  subsets: ['latin'],
  weight: ['400', '700'],
  display: 'swap',
  variable: '--font-martel',
})

const workSans = Work_Sans({
  subsets: ['latin'],
  weight: ['400', '500', '700'],
  display: 'swap',
  variable: '--font-work-sans',
})

export const metadata = {
  title: "Kaktus",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${martel.variable} ${workSans.variable}`}>
      <body className="antialiased">
        {children}
        <Footer/>
      </body>
    </html>
  );
}
