export const products = [
  {
    id: 1,
    name: "Bisküvi",
    image: "/images/nargile.webp",
    description: "",
    price: "400₺",
  },
  {
    id: 2,

    name: "Naturel Meyveli",
    image: "/images/nargile.webp",
    description: "",
    price: "1000₺",
  },
  {
    id: 3,
    name: "JİBİAR Cola Lemon",
    image: "/images/nargile.webp",
    description: "",
    price: "375₺",
  },
  {
    id: 4,
    name: "JİBİAR Turkish Mastic",
    image: "/images/nargile.webp",
    description: "",
    price: "375₺",
  },
  {
    id: 5,
    name: "Special Dominic",
    image: "/images/nargile.webp",
    description: "",
    price: "375₺",
  },
  {
    id: 6,
    name: "Sarı Cappuccino",
    image: "/images/nargile.webp",
    description: "",
    price: "500₺",
  },
  {
    id: 7,
    name: "Tatlı Cadı",
    image: "/images/nargile.webp",
    description: "",
    price: "375₺",
  },
  {
    id: 8,
    name: "Çilek Muz Buz",
    image: "/images/nargile.webp",
    description: "",
    price: "375₺",
  },
  {
    id: 9,
    name: "ALFAKHER Mastic",
    image: "/images/nargile.webp",
    description: "",
    price: "400₺",
  },
  {
    id: 10,
    name: "NAKHLA Vişne",
    image: "/images/nargile.webp",
    description: "",
    price: "450₺",
  },
  {
    id: 11,
    name: "Egzotic",
    image: "/images/nargile.webp",
    description: "",
    price: "500₺",
  },
  {
    id: 12,
    name: "Tütün",
    image: "/images/nargile.webp",
    description: "",
    price: "₺",
  },
  {
    id: 13,
    name: "Kömür",
    image: "/images/nargile.webp",
    description: "",
    price: "₺",
  },
  {
    id: 14,
    name: "ADALYA Love 66",
    image: "/images/nargile.webp",
    description: "",
    price: "375₺",
  },
  {
    id: 15,
    name: "ADALYA Lady Killer",
    image: "/images/nargile.webp",
    description: "",
    price: "375₺",
  },
  {
    id: 16,
    name: "ADALYA İzmir Romantik",
    image: "/images/nargile.webp",
    description: "",
    price: "375₺",
  },
  {
    id: 17,
    name: "ALFAKHER Çift Elma",
    image: "/images/nargile.webp",
    description: "",
    price: "400₺",
  },
  {
    id: 18,
    name: "ALFAKHER Vivident",
    image: "/images/nargile.webp",
    description: "",
    price: "400₺",
  },
  {
    id: 19,
    name: "ALFAKHER Üzüm",
    image: "/images/nargile.webp",
    description: "",
    price: "400₺",
  },
  {
    id: 20,
    name: "ALFAKHER Nane",
    image: "/images/nargile.webp",
    description: "",
    price: "400₺",
  },
  {
    id: 21,
    name: "ALFAKHER 5 Elma",
    image: "/images/nargile.webp",
    description: "",
    price: "400₺",
  },
  {
    id: 22,
    name: "NAKHLA Cappuccino",
    image: "/images/nargile.webp",
    description: "",
    price: "420₺",
  },
  {
    id: 23,
    name: "NAKHLA Anason",
    image: "/images/nargile.webp",
    description: "",
    price: "420₺",
  },
  {
    id: 24,
    name: " JİBİAR Dejavu",
    image: "/images/nargile.webp",
    description: "",
    price: "375₺",
  },
  {
    id: 25,
    name: "Tatlı Cadı Lüle",
    image: "/images/nargile.webp",
    description: "",
    price: "250₺",
  },
  {
    id: 26,
    name: "Bisküvi Lüle",
    image: "/images/nargile.webp",
    description: "",
    price: "275₺",
  },
  {
    id: 27,
    name: "Vivident Lüle",
    image: "/images/nargile.webp",
    description: "",
    price: "275₺",
  },
  {
    id: 28,
    name: "Egzotic Lüle",
    image: "/images/nargile.webp",
    description: "",
    price: "275₺",
  },
  {
    id: 29,
    name: "İce Cola Lüle",
    image: "/images/nargile.webp",
    description: "",
    price: "250₺",
  },
  {
    id: 30,
    name: "Love Lüle",
    image: "/images/nargile.webp",
    description: "",
    price: "250₺",
  },
  {
    id: 31,
    name: "Kaktüs Naturel Lüle",
    image: "/images/nargile.webp",
    description: "",
    price: "450₺",
  },
  {
    id: 32,
    name: "T.Mastic Lüle",
    image: "/images/nargile.webp",
    description: "",
    price: "250₺",
  },
  {
    id: 33,
    name: "Lady Lüle",
    image: "/images/nargile.webp",
    description: "",
    price: "250₺",
  },
  {
    id: 34,
    name: "Mastic Lüle",
    image: "/images/nargile.webp",
    description: "",
    price: "275₺",
  },
  {
    id: 35,
    name: "İzmir Lüle",
    image: "/images/nargile.webp",
    description: "",
    price: "250₺",
  },
  {
    id: 36,
    name: "Cappi Lüle",
    image: "/images/nargile.webp",
    description: "",
    price: "350₺",
  },
  {
    id: 37,
    name: "Gofret Lüle",
    image: "/images/nargile.webp",
    description: "",
    price: "325₺",
  },
  {
    id: 38,
    name: "Pinkman Lüle",
    image: "/images/nargile.webp",
    description: "",
    price: "350₺",
  },
  {
    id: 39,
    name: "5 Elma Lüle",
    image: "/images/nargile.webp",
    description: "",
    price: "275₺",
  },
  {
    id: 40,
    name: "Vişne Lüle",
    image: "/images/nargile.webp",
    description: "",
    price: "300₺",
  },
  {
    id: 41,
    name: "Sarı Cappi Lüle",
    image: "/images/nargile.webp",
    description: "",
    price: "325₺",
  },
  {
    id: 42,
    name: "Dejavu Lüle",
    image: "/images/nargile.webp",
    description: "",
    price: "250₺",
  },
  {
    id: 43,
    name: "ÇilekMuzBuz Lüle",
    image: "/images/nargile.webp",
    description: "",
    price: "250₺",
  },
  {
    id: 44,
    name: "ÇiftElma Lüle",
    image: "/images/nargile.webp",
    description: "",
    price: "275₺",
  },
  {
    id: 45,
    name: "Dominic Lüle",
    image: "/images/nargile.webp",
    description: "",
    price: "250₺",
  },
  {
    id: 46,
    name: "Üzüm Lüle",
    image: "/images/nargile.webp",
    description: "",
    price: "275₺",
  },
  {
    id: 47,
    name: "Üzüm Nane Lüle",
    image: "/images/nargile.webp",
    description: "",
    price: "275₺",
  },
];
