export const products = [
    {
      id: 1,
      name: "True Passion",
      image: "/images/nargile.jpg",
      description:"",
      price: "300₺",
    },
    {
      id: 2,
  
      name: "Special Üçlü Karışım",
      image: "/images/nargile.jpg",
      description: "",
      price: "180₺",
    },
    {
      id: 3,
      name: "Naturel Meyveli",
      image: "/images/nargile.jpg",
      description: "",
      price: "350₺",
    },
    {
        id: 4,
        name: "Kaktüs Special",
        image: "/images/nargile.jpg",
        description: "",
        price: "350₺",
      },
      {
        id: 5,
        name: "Kaktüs Naturel",
        image: "/images/nargile.jpg",
        description: "",
        price: "350₺",
      },
      {
        id: 6,
        name: "Bisküvi",
        image: "/images/nargile.jpg",
        description: "",
        price: "350₺",
      },
      {
        id: 7,
        name: "Cola Lemon",
        image: "/images/nargile.jpg",
        description: "",
        price: "350₺",
      },
      {
        id: 8,
        name: "Escobar",
        image: "/images/nargile.jpg",
        description: "",
        price: "350₺",
      },
      {
        id: 9,
        name: "Plombir",
        image: "/images/nargile.jpg",
        description: "",
        price: "350₺",
      },
      {
        id: 10,
        name: "Turkish Mastic",
        image: "/images/nargile.jpg",
        description: "",
        price: "350₺",
      },
      {
        id: 11,
        name: "Cindirella",
        image: "/images/nargile.jpg",
        description: "",
        price: "350₺",
      },
      {
        id: 12,
        name: "Special Dominic",
        image: "/images/foods/burgerler.jpg",
        description: "",
        price: "350₺",
      },
      {
        id: 13,
        name: "Tatlı Cadı",
        image: "/images/foods/burgerler.jpg",
        description: "",
        price: "350₺",
      },
      {
        id: 14,
        name: "Çilek Muz Buz",
        image: "/images/foods/burgerler.jpg",
        description: "",
        price: "350₺",
      },
      {
        id: 15,
        name: "Inferno",
        image: "/images/foods/burgerler.jpg",
        description: "",
        price: "350₺",
      },
      {
        id: 16,
        name: "Limon Nane",
        image: "/images/foods/burgerler.jpg",
        description: "",
        price: "350₺",
      },
      {
        id: 17,
        name: "Enjoy",
        image: "/images/foods/burgerler.jpg",
        description: "",
        price: "350₺",
      },
      {
        id: 18,
        name: "Master Mix",
        image: "/images/foods/burgerler.jpg",
        description: "",
        price: "350₺",
      },
      {
        id: 19,
        name: "Vişne",
        image: "/images/foods/burgerler.jpg",
        description: "",
        price: "350₺",
      },
      {
        id: 20,
        name: "Alman Tankı",
        image: "/images/foods/burgerler.jpg",
        description: "",
        price: "350₺",
      },
      {
        id: 21,
        name: "Love 66",
        image: "/images/foods/burgerler.jpg",
        description: "",
        price: "350₺",
      },
      {
        id: 22,
        name: "Lady Killer",
        image: "/images/foods/burgerler.jpg",
        description: "",
        price: "350₺",
      },
      {
        id: 23,
        name: "İzmir Romantik",
        image: "/images/foods/burgerler.jpg",
        description: "",
        price: "350₺",
      },
      {
        id: 24,
        name: "Çifte Elma (anason)",
        image: "/images/foods/burgerler.jpg",
        description: "",
        price: "350₺",
      },
      {
        id: 25,
        name: "Vivident",
        image: "/images/foods/burgerler.jpg",
        description: "",
        price: "350₺",
      },
      {
        id: 26,
        name: "Üzüm",
        image: "/images/foods/burgerler.jpg",
        description: "",
        price: "350₺",
      },
      {
        id: 27,
        name: "Yaban",
        image: "/images/foods/burgerler.jpg",
        description: "",
        price: "350₺",
      },
      {
        id: 28,
        name: "Nane",
        image: "/images/foods/burgerler.jpg",
        description: "",
        price: "350₺",
      },
      {
        id: 29,
        name: "5 Elma",
        image: "/images/foods/burgerler.jpg",
        description: "",
        price: "350₺",
      },
      {
        id: 30,
        name: "Cappuccino",
        image: "/images/foods/burgerler.jpg",
        description: "",
        price: "350₺",
      },
      {
        id: 31,
        name: "Çikolata Nane",
        image: "/images/foods/burgerler.jpg",
        description: "",
        price: "350₺",
      },
      {
        id: 32,
        name: "Absolute Zero",
        image: "/images/nargile.jpg",
        description: "",
        price: "350₺",
      },
      {
        id: 33,
        name: "Dejavu",
        image: "/images/nargile.jpg",
        description: "",
        price: "350₺",
      },
      {
        id: 34,
        name: "Ananas Gofret",
        image: "/images/nargile.jpg",
        description: "",
        price: "350₺",
      },
  ];
  