export const products = [
    {
      id: 1,
      name: "Limonata",
      image: "/images/drinks/vitamin-bar/limonata.webp",
      description:"",
      price: "150₺",
    },
    {
      id: 2,
      name: "Karpuz Limonata",
      image: "/images/drinks/vitamin-bar/karpuzlu-limonata.jpg",
      description: "",
      price: "150₺",
    },
    {
      id: 3,
      name: "Çilekli Limonata",
      image: "/images/drinks/vitamin-bar/cilekli-limonata.webp",
      description: "",
      price: "150₺",
    },
    {
        id: 4,
        name: "Portakal Suyu",
        image: "/images/drinks/vitamin-bar/portakal-suyu.webp",
        description: "",
        price: "225₺",
      },
      {
        id: 5,
        name: "Havuç Suyu",
        image: "/images/drinks/vitamin-bar/havuc-suyu.webp",
        description: "",
        price: "225₺",
      },
      {
        id: 6,
        name: "Nar Suyu",
        image: "/images/drinks/vitamin-bar/nar-suyu.jpg",
        description: "",
        price: "275₺",
      },
      {
        id: 7,
        name: "Ananas Suyu",
        image: "/images/drinks/vitamin-bar/ananas.jpg",
        description: "",
        price: "375₺",
      },
      {
        id: 8,
        name: "Elma Suyu",
        image: "/images/drinks/vitamin-bar/elma-suyu.jpg",
        description: "",
        price: "225₺",
      },
      {
        id: 9,
        name: "Full Kokteyl",
        image: "/images/drinks/vitamin-bar/full-kokteyl.webp",
        description: "",
        price: "300₺",
      },
      {
        id: 10,
        name: "C Vitamini",
        image: "/images/drinks/vitamin-bar/c-vitamini.webp",
        description: "",
        price: "275₺",
      },
      {
        id: 11,
        name: "Cool Berry",
        image: "/images/drinks/vitamin-bar/cool-berry.webp",
        description: "",
        price: "180₺",
      },
      {
        id: 12,
        name: "Cool Lime",
        image: "/images/drinks/vitamin-bar/cool-lime.webp",
        description: "",
        price: "175₺",
      },
      {
        id: 13,
        name: "Greyfurt <Suyu></Suyu>",
        image: "/images/drinks/vitamin-bar/greyfurt-suyu.webp",
        description: "",
        price: "225₺",
      },
      {
        id: 14,
        name: "Kombo Ananas",
        image: "/images/drinks/vitamin-bar/ananas.jpg",
        description: "",
        price: "450₺",
      },
  ];
  